export const ROUTES = Object.freeze({
  overview: 'overview',
  groups: 'groups',
  academic: 'academic',
  plan: 'plan',
  work: 'work',
  materials: 'materials',
  search: 'search',
  more: 'more',
  diagnostics: 'diagnostics',
  settings: 'settings',
  data: 'data',
  templates: 'templates',
  server: 'server',
  communication: 'communication',
  substitution: 'substitution',
});

export const ENTITY_STORES = Object.freeze({
  appMeta: 'appMeta',
  schoolYears: 'schoolYears',
  subjects: 'subjects',
  groupIdentities: 'groupIdentities',
  groupInstances: 'groupInstances',
  lessons: 'lessons',
  quickNotes: 'quickNotes',
  tasks: 'tasks',
  reminders: 'reminders',
  materials: 'materials',
  materialLinks: 'materialLinks',
  tags: 'tags',
  entityTags: 'entityTags',
  students: 'students',
  messageTemplates: 'messageTemplates',
  messages: 'messages',
  messageDeliveries: 'messageDeliveries',
  attachments: 'attachments',
  attachmentLinks: 'attachmentLinks',
  lessonTemplates: 'lessonTemplates',
  teachingCycles: 'teachingCycles',
  syncQueue: 'syncQueue',
  syncConflicts: 'syncConflicts',
  auditEvents: 'auditEvents',
  backupSnapshots: 'backupSnapshots',
  substitutionPeriods: 'substitutionPeriods',
  substitutionPlans: 'substitutionPlans',
  substitutionItems: 'substitutionItems',
});

export const APP_EVENTS = Object.freeze({
  routeChanged: 'route:changed',
  themeChanged: 'theme:changed',
  academicChanged: 'academic:changed',
  lessonChanged: 'lesson:changed',
  workChanged: 'work:changed',
  materialChanged: 'material:changed',
  dataChanged: 'data:changed',
  templateChanged: 'template:changed',
  cycleChanged: 'cycle:changed',
  syncChanged: 'sync:changed',
  serverChanged: 'server:changed',
  communicationChanged: 'communication:changed',
  substitutionChanged: 'substitution:changed',
  databaseReady: 'database:ready',
  databaseError: 'database:error',
  diagnosticsUpdated: 'diagnostics:updated',
  toast: 'ui:toast',
});
